
sudo: true
dist: xenial

jobs:
  include:
    - # build project
      branches:
        except:
          - gh-pages
          - master

      if: type = pullrequest

      addons:
        apt:
          packages:
            - libeigen3-dev
            - python-wstool
            - clang
            - clang-format
            - libsdl2-dev

      cache:
          apt: true
          ccache: true

      language: cpp

      matrix:
        include:
        - name: "ROS kinetic"
          env: ROS_DISTRO=kinetic

      env:
        global:
          - SRC_PATH=$(pwd)
          - GH_REPO_NAME: ros.package
          - GH_REPO_REF: github.com/Autonomous-Racing-PG/ros.package.git

      before_install:
        - cd ros_ws
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
        - sudo apt-get update -qq
        - sudo apt-get install -y "ros-${ROS_DISTRO}-desktop-full"
        - source /opt/ros/${ROS_DISTRO}/setup.bash
        - sudo rosdep init
        - rosdep update

      before_script:
        - wstool init
        - wstool up
        - source /opt/ros/${ROS_DISTRO}/setup.bash
        - rosdep install -y --from-paths src --ignore-src --rosdistro ${ROS_DISTRO}

      script:
        - source /opt/ros/${ROS_DISTRO}/setup.bash
        - catkin_make 
        - catkin_make run_tests && catkin_test_results
      
    - # create documentation
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz

      cache:
          apt: true
          ccache: true
      
      env:
        global:
          - SRC_PATH=$(pwd)
          - GH_REPO_NAME: ros.package
          - DOXYFILE: $TRAVIS_BUILD_DIR/docs/master/Doxyfile
          - GH_REPO_REF: github.com/Autonomous-Racing-PG/ros.package.git

      script:
        - cd $TRAVIS_BUILD_DIR
        - chmod 755 ./scripts/travis/doxygen/generate-doxygen-doc.sh
        - ./scripts/travis/doxygen/generate-doxygen-doc.sh